services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js:ro

    
  migrator:
    build: .
    container_name: mongo_migrator
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongo:${DB_PORT}/admin
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
volumes:
  mongo_data:
